name: sphia
description: Sphia - a Proxy Handling Intuitive Application
publish_to: 'none'

version: 1.0.0+12

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  archive: ^3.6.1
  dart_ping: ^9.0.1
  drift: ^2.20.3
  file_picker: ^8.1.2
  fixnum: ^1.1.0
  fl_chart: ^0.69.0
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  grpc: ^4.0.1
  hooks_riverpod: ^2.5.2
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  launch_at_startup: ^0.3.1
  material_symbols_icons: ^4.2788.0
  path: ^1.9.0
  path_provider: ^2.1.4
  protobuf: ^3.1.0
  pub_semver: ^2.1.4
  qr_flutter: ^4.1.0
  quiver: ^3.2.2
  riverpod_annotation: ^2.3.5
  sqlite3_flutter_libs: ^0.5.24
  tray_manager: ^0.2.4
  updat: ^1.3.2
  url_launcher: ^6.3.0
  uuid: ^4.5.1
  validator_regex: ^1.1.1
  window_manager: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.12
  drift_dev: ^2.20.3
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3

dependency_overrides:
  window_manager: ^0.4.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/sphia.db
    - assets/tray_color_off.ico
    - assets/tray_color_on.ico
    - assets/tray_no_color_off.png
    - assets/tray_no_color_on.png
    - assets/logo_about.png
    - assets/app_icon.ico
    - assets/app_icon.png