name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-on-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.1'
      - name: Build
        run: |
          ./lib/script/build.sh
      - name: Publish x86_64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: sphia-linux-amd64
          path: dist/sphia-linux-amd64.AppImage

  build-on-windows-amd64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.1'
      - name: Build
        run: |
          powershell -File .\lib\script\build.ps1
      - name: Publish x86_64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: sphia-windows-amd64
          path: dist/sphia-windows-amd64.exe

  build-on-macos-arm64:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.1'
      - name: Build
        run: |
          ./lib/script/build.sh
      - name: Publish universal artifact
        uses: actions/upload-artifact@v4
        with:
          name: sphia-macos-universal
          path: dist/sphia-macos-universal.dmg

  publish-releases:
    name: Publish releases
    needs: [ build-on-linux-amd64, build-on-windows-amd64, build-on-macos-arm64 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: mkdir artifacts
      - name: Download Linux-x86_64 artifact
        uses: actions/download-artifact@v4
        with:
          name: sphia-linux-amd64
          path: artifacts
      - name: Download Windows-x86_64 artifact
        uses: actions/download-artifact@v4
        with:
          name: sphia-windows-amd64
          path: artifacts
      - name: Download macOS-universal artifact
        uses: actions/download-artifact@v4
        with:
          name: sphia-macos-universal
          path: artifacts
      - name: Get version
        id: get_version
        shell: bash
        run: |
          echo "::set-output name=version::$(head -n 5 pubspec.yaml | tail -n 1 | cut -d ' ' -f 2)"
      - name: Upload to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/sphia-linux-amd64.AppImage,artifacts/sphia-windows-amd64.exe,artifacts/sphia-macos-universal.dmg"
          tag: ${{github.ref_name}}
          bodyFile: changelog/v${{steps.get_version.outputs.version}}.md
          prerelease: contains(github.ref, 'pre')
          allowUpdates: true
          artifactErrorsFailBuild: true
          replacesArtifacts: true
